config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "entries#index"
  resources :entries do
    member do
      get 'checkout'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
    #validates :luggage_no, :c_name, :receiv_by, :receiv_datetime , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @time = Time.new.strftime("%Y-%m-%d %H:%M:%S")
    
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def checkout
   

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:luggage_no, :c_name, :receiv_by, :receiv_datetime, :return_by, :return_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Luggage no:</strong>
    <%= entry.luggage_no %>
  </p>

  <p>
    <strong>C name:</strong>
    <%= entry.c_name %>
  </p>

  <p>
    <strong>Receiv by:</strong>
    <%= entry.receiv_by %>
  </p>

  <p>
    <strong>Receiv datetime:</strong>
    <%= entry.receiv_datetime %>
  </p>

  <p>
    <strong>Return by:</strong>
    <%= entry.return_by %>
  </p>

  <p>
    <strong>Return datetime:</strong>
    <%= entry.return_datetime %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :luggage_no, style: "display: block" %>
    <%= form.number_field :luggage_no %>
  </div>

  <div>
    <%= form.label :c_name, style: "display: block" %>
    <%= form.text_field :c_name %>
  </div>

  <div>
    <%= form.label :receiv_by, style: "display: block" %>
    <%= form.text_field :receiv_by %>
  </div>

  <div>
    <%= form.label :receiv_datetime, style: "display: block" %>
    <%= form.datetime_field :receiv_datetime, value: @time %>
  </div>

  <div>
    <%#= form.label :return_by, style: "display: block" %>
    <%#= form.text_field :return_by %>
  </div>

  <div>
    <%#= form.label :return_datetime, style: "display: block" %>
    <%#= form.datetime_field :return_datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/_submit_form.html.erb
submit

app/views/entries/checkout.html.erb
<%= render "submit_form", entry: @entry %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<div class="rows">
  <div class="col-12">
    <h1>Luggage List</h1>
    <h3><%= link_to "New Entry", new_entry_path %></h3>
  </div>

  <div class="col-12">
    <p style="color: green"><%= notice %></p>
  </div>

  <div id="entries" class="col-12">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
          <tr>
            <td scope="row"><%= entry.luggage_no %></td>
            <td><%= entry.c_name %></td>
            <td><%= entry.receiv_by %></td>
            <td><%= entry.receiv_datetime %></td>
            <td> 
              <%= link_to "EDIT", edit_entry_path(entry) %> |
              <%= link_to "Check Out", checkout_entry_path(entry) %> |
              <%= button_to "Destroy this entry", entry, method: :delete %>
              </td>
          </tr>
        <% end %>
        
      </tbody>
    </table>
    
  </div>

</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luggage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>